-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-19 00:41:40 EDT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



DROP TABLE Ingredientes CASCADE CONSTRAINTS;

DROP TABLE Panes CASCADE CONSTRAINTS;

DROP TABLE PanReceta CASCADE CONSTRAINTS;

DROP TABLE Pedidos CASCADE CONSTRAINTS;

DROP TABLE PedidoPan CASCADE CONSTRAINTS;

DROP TABLE Recetas CASCADE CONSTRAINTS;

DROP TABLE RecetaIngrediente CASCADE CONSTRAINTS;

DROP TABLE Sucursales CASCADE CONSTRAINTS;

DROP TABLE Stock CASCADE CONSTRAINTS;

DROP TABLE StockActivity CASCADE CONSTRAINTS;

CREATE TABLE Ingrediente (
    IngredienteId NUMBER(4) NOT NULL,
    Nombre        VARCHAR2(250 CHAR),
    Proveedor     VARCHAR2(250 CHAR),
    CostoUnitario NUMBER(4),
    FechaCompra   DATE,
    IsActive      CHAR(1)
);

ALTER TABLE ingredientes ADD CONSTRAINT ingrediente_pk PRIMARY KEY ( ingredienteid );

CREATE TABLE Panes (
    PanId             NUMBER(4) NOT NULL,
    Nombre            VARCHAR2(75),
    PrecioUnitario    VARCHAR2(75),
    Descripcion       VARCHAR2(1250),
    TiempoPreparacion VARCHAR2(75),
    IsActive          CHAR(1)
);

COMMENT ON COLUMN pan.panid IS
    'Id del tipo de pan a producir';

COMMENT ON COLUMN pan.nombre IS
    'Nombre del tipo de pan';

ALTER TABLE pan ADD CONSTRAINT pan_pk PRIMARY KEY ( panid );

CREATE TABLE PanReceta (
    PanId       NUMBER(4) NOT NULL,
    RecetaId NUMBER(4) NOT NULL
);

ALTER TABLE PanReceta ADD CONSTRAINT pan_receta_pk PRIMARY KEY ( PanId,
                                                                  RecetaId );

CREATE TABLE Pedidos (
    PedidoId            NUMBER(4) NOT NULL,
    FechaPedido         DATE,
    Ruta                VARCHAR2(75 CHAR),
    Estado              VARCHAR2(250 CHAR),
    Comentarios         VARCHAR2(250 CHAR),
    IsActive            CHAR(1),
    SucursalId NUMBER(4) NOT NULL
);

ALTER TABLE Pedidos ADD CONSTRAINT pedido_pk PRIMARY KEY ( PedidoId,
                                                          Sucursalid );

CREATE TABLE PedidoPan (
    PanId         NUMBER(4) NOT NULL,
    PedidoId   NUMBER(4) NOT NULL,
    Cantidad NUMBER(4),
    Comentarios VARCHAR2(250 CHAR),
    IsActive            CHAR(1),
    Id NUMBER(4) NOT NULL
);

ALTER TABLE PedidoPan
    ADD CONSTRAINT pedido_pan_pk PRIMARY KEY ( PanId,
                                               PedidoId,
                                               SucursalId );

CREATE TABLE Recetas (
    RecetaId    NUMBER(4) NOT NULL,
    Descripcion VARCHAR2(250 CHAR),
    IsActive    CHAR(1),
    PanId    NUMBER(4) NOT NULL
);

ALTER TABLE Receta ADD CONSTRAINT receta_pk PRIMARY KEY ( RecetaId );

CREATE TABLE RecetaIngrediente (
    RecetaId           NUMBER(4) NOT NULL,
    IngredienteId NUMBER(4) NOT NULL,
    Descripcion VARCHAR2(250 CHAR),
    Cantidad VARCHAR2(20 CHAR),
    IsActive    CHAR(1),
    Id NUMBER(4) NOT NULL
);

ALTER TABLE RecetaIngrediente ADD CONSTRAINT receta_ingrediente_pk PRIMARY KEY ( RecetaId,
                                                                                  IngredienteId );

CREATE TABLE Sucursales (
    SucursalId       NUMBER(4) NOT NULL,
    Nombre           VARCHAR2(250 CHAR),
    Direccion        VARCHAR2(750 CHAR),
    NumeroTelefono   VARCHAR2(30 CHAR),
    GerenteSucursal  VARCHAR2(75 CHAR),
    HorariOoperacion VARCHAR2(175 CHAR),
    IsActive         CHAR(1)
);

ALTER TABLE Sucursal ADD CONSTRAINT sucursal_pk PRIMARY KEY ( SucursalId );

CREATE TABLE Stock (
    StockId         NUMBER(4) NOT NULL,
    PanId   NUMBER(4) NOT NULL,
    Cantidad NUMBER(4) NOT NULL,
    Notas VARCHAR2 (250 CHAR),
    FechaCreacion DATE,
    FechaModificacion DATE,
    IsActive CHAR(1)
);


CREATE TABLE StockActivity (
    Id NUMBER(4) NOT NULL,
    StockId         NUMBER(4) NOT NULL,
    PanId   NUMBER(4) NOT NULL,
    Cantidad NUMBER(4) NOT NULL,
    Notas VARCHAR2 (250 CHAR),
    FechaCreacion DATE,
    FechaModificacion DATE
);

ALTER TABLE Stock
    ADD CONSTRAINT stock_pan_fk FOREIGN KEY ( PanId )
        REFERENCES Panes ( PanId );
        
ALTER TABLE PanReceta
    ADD CONSTRAINT pan_receta_pan_fk FOREIGN KEY ( PanId )
        REFERENCES Pan ( PanId );

ALTER TABLE PanReceta
    ADD CONSTRAINT pan_receta_receta_fk FOREIGN KEY ( RecetaId )
        REFERENCES receta ( RecetaId );

ALTER TABLE PedidoPan
    ADD CONSTRAINT pedido_pan_pan_fk FOREIGN KEY ( PanId )
        REFERENCES Pan ( PanId );

ALTER TABLE PedidoPan
    ADD CONSTRAINT pedido_pan_pedido_fk FOREIGN KEY ( PedidoId,
                                                      SucursalId )
        REFERENCES Pedido ( PedidoId,
                            SucursalId );

ALTER TABLE RecetaIngrediente
    ADD CONSTRAINT receta_ingrediente_ingrediente_fk FOREIGN KEY ( IngredienteId )
        REFERENCES Ingrediente ( IngredienteId );

ALTER TABLE RecetaIngrediente
    ADD CONSTRAINT receta_ingrediente_receta_fk FOREIGN KEY ( RecetaId )
        REFERENCES Receta ( RecetaId );

ALTER TABLE Pedido
    ADD CONSTRAINT SucursalPedido FOREIGN KEY ( SucursalId )
        REFERENCES Sucursal ( SucursalId );



